linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - ineffassign
    - misspell
    - unconvert
    - nilerr


#govet: Анализирует код на подозрительные конструкции.
#errcheck: Проверяет обработку ошибок.
#staticcheck: Выявляет ошибки и проблемы производительности.
#gosec: Проверяет на уязвимости безопасности.
#ineffassign: Находит ненужные присваивания.
#misspell: Ищет опечатки.
#unconvert: Выявляет лишние преобразования типов.
#nilerr: Проверяет сравнения ошибок с nil.